name: StreamCraft
version: ${project.version}
main: me.crazycranberry.streamcraft.StreamCraft
api-version: 1.20
authors: [CrazyCranberry]
description: A plugin that allows stream viewers to interact with the minecraft world.
commands:
  screfresh:
    description: Refresh yml configurations
    permission: admin
    permission-message: You do not have permission to refresh.
  screconnect:
    description: Restart the Twitch WebSocket connection
    permission: admin
    permission-message: You do not have permission to refresh.
  cf:
    description: Only for testing. Delete me.
permissions:
  admin:
    description: Vanilla Hunger Games Admin permission
    default: op
